### ISSUE TITLE
Conda building error

### ISSUE THREAD

**Issue by AlexKurek** [MITHaystack/srt-py#19]
`conda build srt-py`
does not work due to dependency issues:
```
    conda.exceptions.PackagesNotFoundError: The following packages are not available from current channels:

      - yamale
      - soapysdr-module-rtlsdr
      - soapysdr
      - rtl-sdr
      - gnuradio-zeromq
      - gnuradio-osmosdr
      - gnuradio-core
      - digital_rf
      - dash-bootstrap-components
```

I also could not build it using:
`conda build srt-py --channel conda-forge --python 3.11.7`
nor
`conda build srt-py --channel conda-forge --python 3.10.13`

**Comment by ryanvolz** [comment]
This is happening because the recipe builds against the most recent version of Python (3.12) no matter what you might specify on the command line, and `digital_rf` doesn't yet have a release that is compatible with Python 3.12. I put together [a fix](https://github.com/MITHaystack/srt-py/pull/20) that makes the conda package independent of the Python version, so it will work even without an update to `digital_rf`.

**Comment by AlexKurek** [comment]
Thank you, that was quick. It worked like this:

```
git clone -b update-conda-recipe https://github.com/ryanvolz/srt-py
conda build srt-py --channel conda-forge
```

I had to ude conda-forge, so maybe it would be good to update the instruction here: git clone -b update-conda-recipe https://github.com/ryanvolz/srt-py
conda build srt-py --channel conda-forge

**Comment by AlexKurek** [comment]
@ryanvolz However, after installing like so:

```
conda update --all
conda install conda-build conda-verify
git clone -b update-conda-recipe https://github.com/ryanvolz/srt-py
conda create -y --name srtpy
conda activate srtpy
conda build srt-py --channel conda-forge
conda build purge
mkdir srtpy-config/
cp /home/kurek/srt-py/config/* ~/srtpy-config/
rm -rf ~/srt-py/
conda deactivate
```

Im trying tu run it:
```
conda activate srtpy
python ./miniconda3/pkgs/srt-py-1.1.1-py_0/python-scripts/srt_runner.py --config_dir=~/srtpy-config/
```
and getting:
```
  File "./miniconda3/pkgs/srt-py-1.1.1-py_0/python-scripts/srt_runner.py", line 12, in <module>
    from waitress import serve
ImportError: No module named waitress
```

**Comment by AlexKurek** [comment]
@ryanvolz After installing like so:
```
conda install conda-build conda-verify
git clone -b update-conda-recipe https://github.com/ryanvolz/srt-py
conda create -y --name srtpy
conda activate srtpy
conda build srt-py --channel conda-forge --no-test
conda build purge
mkdir srtpy-config/
cp /home/kurek/srt-py/config/* ~/srtpy-config/
rm -rf ~/srt-py/
conda deactivate
```

Im trying to run it:
```
conda activate srtpy
python ./miniconda3/pkgs/srt-py-1.1.1-py_0/python-scripts/srt_runner.py --config_dir=~/srtpy-config/
```
and getting:
```
  File "./miniconda3/pkgs/srt-py-1.1.1-py_0/python-scripts/srt_runner.py", line 12, in <module>
    from waitress import serve
ImportError: No module named waitress
```
Doing:
`conda list srtpy`
returns empty list.

**Comment by ryanvolz** [comment]
There's nothing in your `srtpy` environment because you're missing the step of installing the package that you built:
```
conda install --use-local srt-py
```

I should update the README too once we have a list of steps that work.

**Comment by AlexKurek** [comment]
Ok, thank you. So now it is:

```
conda update -y --all
conda install -y conda-build conda-verify
git clone -b update-conda-recipe https://github.com/ryanvolz/srt-py
conda create -y --name srtpy
conda activate srtpy
conda build srt-py --channel conda-forge --no-test
conda install --use-local srt-py
```
and Im getting:
```
Channels:
 - local
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - nothing provides dash-bootstrap-components needed by srt-py-1.1.1-py_0

Could not solve for environment specs
The following package could not be installed
└─ srt-py is not installable because it requires
   └─ dash-bootstrap-components, which does not exist (perhaps a missing channel).
```

**Comment by ryanvolz** [comment]
Not having the conda-forge channel by default is what's causing this error now. How about this sequence:
```
(navigate to srt-py directory)
conda install conda-build conda-verify
conda build -c conda-forge recipe
conda create -n srtpy
conda activate srtpy
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install --use-local srt-py
```

**Comment by AlexKurek** [comment]
Its working! Im getting:
```
Configuration Directory Does Not Exist
Please Refer to the Documentation for Creating a Config Directory
```
(I havent done that yet).

**Comment by AlexKurek** [comment]
It works. I have not connected the telescope, so it crashes. Is this the right way to crash in such a case? (I have not changed anything in the config files yet).

Also there are a few `AstropyDeprecationWarning`s.


```
Downloading https://datacenter.iers.org/data/9/finals2000A.all [Done]
WARNING: AstropyDeprecationWarning: The get_moon function is deprecated and may be removed in a future version.
        Use get_body("moon") instead. [srt.daemon.utilities.object_tracker]
WARNING:astropy:AstropyDeprecationWarning: The get_moon function is deprecated and may be removed in a future version.
        Use get_body("moon") instead.
WARNING: AstropyDeprecationWarning: The get_moon function is deprecated and may be removed in a future version.
        Use get_body("moon") instead. [srt.daemon.utilities.object_tracker]
WARNING:astropy:AstropyDeprecationWarning: The get_moon function is deprecated and may be removed in a future version.
        Use get_body("moon") instead.
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.9.2
built-in source types: file fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya
Process RadioProcessTask-1:1:
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/radio_control/radio_process/radio_process.py", line 749, in main
    tb = top_block_cls(
         ^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/radio_control/radio_process/radio_process.py", line 103, in __init__
    self.osmosdr_source_0 = osmosdr.source(
                            ^^^^^^^^^^^^^^^
RuntimeError: No RTL-SDR devices found!
Setting Frequency
Setting Sample Rate
Setting Motor Azimuth
Setting Motor Elevation
Setting Motor GalLat
Setting Motor GalLon
Setting Object Tracking
Setting System Temp
Setting Calibration Temp
Setting Calibration Power
Setting Calibration Values
Setting Is Running
Exception in thread Thread-5 (update_radio_settings):
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/daemon.py", line 641, in update_radio_settings
    call(value)
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/xmlrpc/client.py", line 1122, in __call__
    return self.__send(self.__name, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/xmlrpc/client.py", line 1464, in __request
    response = self.__transport.request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/xmlrpc/client.py", line 1166, in request
    return self.single_request(host, handler, request_body, verbose)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/xmlrpc/client.py", line 1178, in single_request
    http_conn = self.send_request(host, handler, request_body, verbose)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/xmlrpc/client.py", line 1291, in send_request
    self.send_content(connection, request_body)
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/xmlrpc/client.py", line 1321, in send_content
    connection.endheaders(request_body)
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/http/client.py", line 1289, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/http/client.py", line 1048, in _send_output
    self.send(msg)
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/http/client.py", line 986, in send
    self.connect()
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/http/client.py", line 952, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
```

**Comment by AlexKurek** [comment]
We have H180 motor, so I changed in the config file:
`MOTOR_TYPE: H180MOUNT`
I got:
```
Process SRT-Daemon:
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kurek/./miniconda3/envs/srtpy/bin/srt_runner.py", line 19, in run_srt_daemon
    daemon = srt_d.SmallRadioTelescopeDaemon(configuration_dir, configuration_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/daemon.py", line 115, in __init__
    self.rotor = Rotor(
                 ^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/rotors.py", line 58, in __init__
    self.motor = H180Motor(port, baudrate, az_limits, el_limits)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/motors.py", line 352, in __init__
    Motor.__init__(self, port, az_limits, el_limits)
TypeError: Motor.__init__() missing 1 required positional argument: 'el_limits'
Exception ignored in: <function Motor.__del__ at 0x7f68a291dee0>
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/motors.py", line 88, in __del__
    if self.serial is not None and self.serial.is_open:
       ^^^^^^^^^^^
AttributeError: 'H180Motor' object has no attribute 'serial'
```
The motor is not connected but I thought I would report this since Im not sure if this is the right way it should crash?

**Comment by AlexKurek** [comment]
After connecting RTL-SDR and running headless Im getting:

`$ python ./miniconda3/envs/srtpy/bin/srt_runner.py --config_dir=/home/akurek/srtpy-config/ status`

```
usage: srt_runner.py [-h] [--config_dir config_dir] [--config_file_name config_file_name] [--dash_only]
srt_runner.py: error: unrecognized arguments: status
```

**Comment by AlexKurek** [comment]
Other than that its working, I was able to run GUI after connecting RTL-SDR and setting `MOTOR_TYPE: NONE` and record a signal.

**Comment by AlexKurek** [comment]
@ryanvolz We connected H180 through RS-USB adapter based on CH340 chip. We got again: https://github.com/MITHaystack/srt-py/issues/19#issuecomment-1933687619 . I added:
`print (self.el_limits)`
here: https://github.com/MITHaystack/srt-py/blob/master/srt/daemon/daemon.py#L115
and got: (`7.6, 80.0)` as im my config file.

May this be a Python bug?
(Should we report issues here or rather at https://github.com/MITHaystack/srt-py?)

**Comment by AlexKurek** [comment]
We have H180 and wheter itis connected or not we are getting:

```
Process SRT-Daemon:
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kurek/./miniconda3/envs/srtpy/bin/srt_runner.py", line 19, in run_srt_daemon
    daemon = srt_d.SmallRadioTelescopeDaemon(configuration_dir, configuration_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/daemon.py", line 115, in __init__
    self.rotor = Rotor(
                 ^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/rotors.py", line 58, in __init__
    self.motor = H180Motor(port, baudrate, az_limits, el_limits)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/motors.py", line 352, in __init__
    Motor.__init__(self, port, az_limits, el_limits)
TypeError: Motor.__init__() missing 1 required positional argument: 'el_limits'
Exception ignored in: <function Motor.__del__ at 0x7f68a291dee0>
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/motors.py", line 88, in __del__
    if self.serial is not None and self.serial.is_open:
       ^^^^^^^^^^^
AttributeError: 'H180Motor' object has no attribute 'serial'
```
I did `print(dir(H180Motor))` before this `if` and got:
`['AZCOUNTS_PER_DEG', 'ELCOUNTS_PER_DEG', '__abstractmethods__', '__class__', '__del__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slots__', '__str__', '__subclasshook__', '__weakref__', '_abc_impl', 'point', 'send_h180_cmd', 'status']`
but I have no idea what to do about this.

**Comment by AlexKurek** [comment]
This sequence is working.

**Comment by AlexKurek** [comment]
This sequence is working.

In summary, this is what I have to do to start it SRT-Py:

```
# conda update -y --all
conda install -y conda-build conda-verify
git clone -b update-conda-recipe https://github.com/ryanvolz/srt-py # https://github.com/MITHaystack/srt-py/issues/19#issuecomment-1930609080
conda build -c conda-forge srt-py # --no-test
conda create -y -n srtpy
conda activate srtpy
conda config --env --add channels conda-forge
conda config --env --set channel_priority strict
conda install -y --use-local srt-py
mkdir srtpy-config/
cp -r ~/srt-py/config/{config.yaml,schema.yaml,sky_coords.csv} ~/srtpy-config/
cp -r ~/srt-py/examples/example_cmd_file.txt ~/
rm -rf ~/srt-py/
sudo ln -s ~/miniconda3/envs/srtpy/lib/udev/rules.d/rtl-sdr.rules /etc/udev/rules.d/ # enable udev device setup of rtl-sdr hardware
sudo udevadm control --reload && sudo udevadm trigger # reload your udev rules
conda deactivate
conda build purge
sudo apt purge brltty # https://askubuntu.com/questions/1403705/dev-ttyusb0-not-present-in-ubuntu-22-04
sudo rm -rv /var/lib/BrlAPI/
sudo usermod -a -G tty,dialout $USER # https://github.com/esp8266/source-code-examples/issues/26#issuecomment-320999460 proper logout required after this
```

**Comment by AlexKurek** [comment]
I have updated the installation instructions in my fork:
https://github.com/AlexKurek/srt-py/blob/master/README.md#building-the-conda-package-locally
