### ISSUE TITLE
AttributeError: 'H180Motor' object has no attribute 'serial'

### ISSUE THREAD

**Issue by AlexKurek** [MITHaystack/srt-py#21]
We have H180 and wheter itis connected or not we are getting:

```
Process SRT-Daemon:
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/kurek/./miniconda3/envs/srtpy/bin/srt_runner.py", line 19, in run_srt_daemon
    daemon = srt_d.SmallRadioTelescopeDaemon(configuration_dir, configuration_dict)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/daemon.py", line 115, in __init__
    self.rotor = Rotor(
                 ^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/rotors.py", line 58, in __init__
    self.motor = H180Motor(port, baudrate, az_limits, el_limits)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/motors.py", line 352, in __init__
    Motor.__init__(self, port, az_limits, el_limits)
TypeError: Motor.__init__() missing 1 required positional argument: 'el_limits'
Exception ignored in: <function Motor.__del__ at 0x7f68a291dee0>
Traceback (most recent call last):
  File "/home/kurek/miniconda3/envs/srtpy/lib/python3.11/site-packages/srt/daemon/rotor_control/motors.py", line 88, in __del__
    if self.serial is not None and self.serial.is_open:
       ^^^^^^^^^^^
AttributeError: 'H180Motor' object has no attribute 'serial'
```
I modified https://github.com/MITHaystack/srt-py/blob/master/srt/daemon/rotor_control/motors.py#L352 to:
`Motor.__init__(self, port, az_limits=(-0.7,359), el_limits=(8.4,80), baudrate=2400), `
and the error is gone.

**Comment by AlexKurek** [comment]
FYI: Im also getting these warnings in loop:
```
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 2
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
```
And this one during env activation:
```
$ conda activate srtpy
WARNING: No ICDs were found. Either,
- Install a conda package providing a OpenCL implementation (pocl, oclgrind, intel-compute-runtime, beignet) or 
- Make your system-wide implementation visible by installing ocl-icd-system conda package.
```
I did:
`conda install -c conda-forge ocl-icd-system`
but the warning is still there.

**Comment by AlexKurek** [comment]
Also its not finding default config dir (https://github.com/MITHaystack/srt-py/blob/master/bin/srt_runner.py#L44).
I have to do: `srt_runner.py --config_dir=~/srtpy-config/`. Maybe os.path.expanduser() is needed (https://stackoverflow.com/a/2057072)?
