### ISSUE TITLE
Conda build issue 

### ISSUE THREAD

**Issue by ansondaloisio** [MITHaystack/srt-py#28]
On Mac OSX 12.1, conda-build srt-py results in the following error. 

> Traceback (most recent call last):
>   File "/Users/ansondaloisio/opt/anaconda3/bin/conda-build", line 11, in <module>
>     sys.exit(main())
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 488, in main
>     execute(sys.argv[1:])
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 477, in execute
>     outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
>     return build_tree(
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 3088, in build_tree
>     packages_from_this = build(metadata, stats,
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 2128, in build
>     create_build_envs(top_level_pkg, notest)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda_build/build.py", line 1985, in create_build_envs
>     environ.get_install_actions(m.config.test_prefix,
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda_build/environ.py", line 799, in get_install_actions
>     actions = install_actions(prefix, index, specs, force=True)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
>     return f(*args, **kwds)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/plan.py", line 473, in install_actions
>     txn = solver.solve_for_transaction(prune=prune, ignore_pinned=not pinned)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
>     unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
>     final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 313, in solve_final_state
>     ssc = self._add_specs(ssc)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/core/solve.py", line 707, in _add_specs
>     conflicts = ssc.r.get_conflicting_specs(tuple(MatchSpec(_)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 1106, in get_conflicting_specs
>     C = r2.gen_clauses()
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
>     return f(*args, **kwds)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 909, in gen_clauses
>     for ms in self.ms_depends(prec):
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/resolve.py", line 793, in ms_depends
>     deps = [MatchSpec(d) for d in prec.combined_depends]
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/models/records.py", line 340, in combined_depends
>     result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 476, in merge
>     reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 476, in <lambda>
>     reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 507, in _merge
>     final = this_component.merge(that_component)
>   File "/Users/ansondaloisio/opt/anaconda3/lib/python3.9/site-packages/conda/models/match_spec.py", line 758, in merge
>     raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
> ValueError: Incompatible component merge:
>   - 'mpi_mpich_*'
>   - 'mpi_mpich_tempest*'

**Comment by AlexKurek** [comment]
This is a know error in Conda on Mac: https://github.com/conda/conda/issues/11442.
